# Generated by Django 2.0.3 on 2018-04-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='todo_status',
            field=models.CharField(max_length=200),
        ),
    ]
