# Generated by Django 2.0.3 on 2018-03-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_photo',
            field=models.ImageField(blank=True, upload_to='contact/photo/'),
        ),
    ]
